# Student Computer Lab Toolkit - Legacy Edition
#  (main 9c4c5afe47399ed937c4e4a54551d60b55483824)
# 本文件编码为 UTF-8。
[crack_restore]
crack_when_launching: true
hijack_image: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
