# Student Computer Lab Toolkit - Legacy Edition
# v7.2.1 (main a13479b3f6e2e85acfcfe4d2f7f2c6e745667052)
# UTF-8 编码
[crack_restore]
crack_at_startup: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
