# Student Computer Lab Toolkit - Mainline Edition
# v7.2.2 (main 789d36a649645b7b38cc16efe63ab4c2f18ac0b5)
# UTF-8 编码
[crack_restore]
crack_at_startup: true
suspend_process: true
[window]
forced_show: true
[custom_rules]
